### ISSUE TITLE
Close & config button barely visible

### ISSUE THREAD

**Issue by jerone** [mrodalgaard/atom-expose#1]
Create package! One issue, the close and config buttons are barely visible. I'm guessing this is a theme issue. I'm using the default "One Light" theme.

![2015-06-28 14_55_47-program manager](https://cloud.githubusercontent.com/assets/55841/8396457/5f9bd8f4-1da6-11e5-94d1-03538d4e7923.png)

**Comment by mrodalgaard** [comment]
Closed with 6e13d33316bdd47d4a605c871b0151b592419532. Thank you @jerone.
