### ISSUE TITLE
Tab names for duplicate file names

### ISSUE THREAD

**Issue by art-solopov** [mrodalgaard/atom-expose#18]
![-tasks_widget rb - -home-user-projects-sqteam - atom](https://cloud.githubusercontent.com/assets/5079987/11209695/d96b854c-8d33-11e5-9ff3-f088d0bb1c4e.png)

Even with [Smart tab names](https://atom.io/packages/smart-tab-name) package installed, the tab names are still the same for the same-named files.

**Comment by mrodalgaard** [comment]
70abe0d5fd83ce65520542617bb94241ac24519b uses [Atom tab bar](https://github.com/atom/tabs) long title if two files with the same name is open.

I do not believe the smart-tab-name package can be used here. The package uses the following line to edit each tab bar DOM element directly:

``` js
tabs = atom.views.getView(atom.workspace).querySelectorAll("ul.tab-bar>li.tab[data-type='TextEditor']> div.title[data-path='#{path.replace(/\\/g,"\\\\")}']")
```

I do not want to have to check each DOM tab element for extra information.
