### ISSUE TITLE
Close on core:cancel

### ISSUE THREAD

**Issue by olmokramer** [mrodalgaard/atom-expose#2]
It would be nice if the expose view would close when the `core:cancel` command is triggered. I'm quite used to using the <kbd>escape</kbd> key to close stuff in Atom. Other than that, amazing work! :)

**Comment by eboracus** [comment]
I was just heading in to raise the same point :) tried hitting escape a few times, no response... 'sad face'. It is worth noting that clicking on the background does close the view, as would be expected a la OS X expose. But it'd be good to have both complimentary exits.

It might be just me I don't know, but for some reason I find being able to use esc a strangely satisfying (low effort, certain response maybe) way of closing things.

**Comment by olmokramer** [comment]
It's not just you :wink:

**Comment by mrodalgaard** [comment]
This is fixed in bae5b2dde7557a04c9b7370881ab660537811539 and documented in 433684599f443d84da442ebbe6486eaa1b9da4e7 .

Thanks for the input.

**Comment by olmokramer** [comment]
Cool, thanks!
