### ISSUE TITLE
Not showing thumbnail preview 

### ISSUE THREAD

**Issue by bensk** [mrodalgaard/atom-expose#23]

**Comment by meyercm** [comment]
Also seeing no preview, OS X 10.10.4
Expose v0.11.1
Atom v1.7.4

**Comment by itdoell** [comment]
Minimap preview isn't being displayed.

OS X 10.11.5
Expose v0.11.1
Minimap v4.24.3
Atom v1.7.4

Update -- This seems to occur when minimap's "Absolute Mode" is set to false. Switching on Absolute Mode will correct the issue.

```
minimap:
    absoluteMode: false
```

![absolute-false](https://cloud.githubusercontent.com/assets/1771967/15748134/7a30ad6e-2892-11e6-8921-b0e9f236f5e1.png)

```
minimap:
    absoluteMode: true
```

![absolute-true](https://cloud.githubusercontent.com/assets/1771967/15748145/83ab692e-2892-11e6-859b-aed8adf335a0.png)

**Comment by mrodalgaard** [comment]
Thank you all, especially @itdoell for spotting that it was the absolute mode that caused the problem. This is fixed in the new release.

**Comment by bensk** [comment]
Thank you, @mrodalgaard!
