### ISSUE TITLE
Search Bar On Expose View?

### ISSUE THREAD

**Issue by ChristopherFunk** [mrodalgaard/atom-expose#27]
Would it be possible to have a search bar on the expose view? Sometimes I have a tonne of tabs open and it would be wonderful to be able to just start typing away if I know the tab name 😄 Rather than looking over the numerous boxes.

Preferably a search bar that has auto focus so you can start typing right away?

**Comment by mrodalgaard** [comment]
I like this idea! I will have a look at it when I have more free time.
