### ISSUE TITLE
More than ~15 tabs overflows the screen

### ISSUE THREAD

**Issue by eboracus** [mrodalgaard/atom-expose#3]
I see that with more than three rows (5 columns wide) that the 4th and subsequent rows start to be forced off the bottom of the page. It would be good to make the default view scrollable maybe (or allow the thumbnails to become gradually smaller, though scrolling I guess would be better if it does slow things down so much).

**Comment by mrodalgaard** [comment]
Fixed with 14dd8e8d114725b0cb63af5da3f7c7b943f742a1. Thanks for the feedback.
