### ISSUE TITLE
Selecting tab with keybinding doesn't hide the expose view

### ISSUE THREAD

**Issue by olmokramer** [mrodalgaard/atom-expose#5]
When I click on a tab in the expose view, it hides the expose view. But when I use a keybinding (<kbd>1</kbd>-<kbd>9</kbd>) the expose view stays visible. I would expect the keybindings to behave the same as clicking.

**Comment by mrodalgaard** [comment]
Good spotted. Fixed with 5f88147bab58684f24217a954cbd712d4fcaf303 included in next release.

**Comment by olmokramer** [comment]
Thanks!
