### ISSUE TITLE
Feature request: animation on hide

### ISSUE THREAD

**Issue by olmokramer** [mrodalgaard/atom-expose#6]
Just because it would look so much prettier :)

**Comment by mrodalgaard** [comment]
I started with this behaviour, but disliked it in most scenarios. It just takes too long and slows interaction. It doesn't feel natural to the user flow.

**Comment by olmokramer** [comment]
I see, thanks for explaining. Would you consider adding it as an option?

**Comment by mrodalgaard** [comment]
This feature will not be added as an option, since it does not add value. You might be able to fix this with a custom stylesheet.
