### ISSUE TITLE
Feature request: Ability to change Exposé toggle shortcut.

### ISSUE THREAD

**Issue by Pitu** [mrodalgaard/atom-expose#7]
In my case I would prefer to be able to launch expose by using ctrl + space . It would be nice to have a feature to assign our own shortcut for it.

Great work!

**Comment by mrodalgaard** [comment]
This is done using default Atom feature. Do the following:
1. Go to `Settings` -> `Keybindings`
2. Search for `expose`
3. Click copy for `expose:toggle`
4. Paste into your `keymap.cson` and edit key combination to your needs
5. Test with `Key Binding Resolver` enabled to see how it works

See [keymaps](https://atom.io/docs/lastest/advanced/keymaps) for more info.
