### ISSUE TITLE
Doesn't work well with Atom Material UI Theme

### ISSUE THREAD

**Issue by rsylvian** [mrodalgaard/atom-expose#9]
<img width="1440" alt="screen shot 2015-08-06 at 2 32 31 pm" src="https://cloud.githubusercontent.com/assets/1449325/9123964/ff6ebec2-3c47-11e5-8813-4dfbec7a72c5.png">

**Comment by laughedelic** [comment]
+1

**Comment by mrodalgaard** [comment]
There are a lot suddle differences with tab bars on other themes. I think I'll have to rethink the mimicking of theme styled tab bar and just create a static look with background that matches current theme.

**Comment by ritz4-5** [comment]
+1

**Comment by mrodalgaard** [comment]
0a38f0b4c7d0ba9f28b15db63481fe037ebaf139 uses own styling of tabs with themes background color. This should look decent with most themes. Could somebody verify with Material UI?

**Comment by mrodalgaard** [comment]
Newest package release ([0.5.0](https://github.com/mrodalgaard/atom-expose/commit/cca7154d14de24767dc24147b9f489e62e6ecea6)) includes stand alone styling of expose tabs, which should make them visible in Material UI as well.

**Comment by rsylvian** [comment]
I've seen some changes but still doesn't work :/

**Comment by ritz4-5** [comment]
It works in Material UI. thx!

**Comment by mrodalgaard** [comment]
@MyBoon could you elaborate. Are the tab body views still missing like the screenshot you posted? Have you tried restarting Atom after package update?

**Comment by wldcordeiro** [comment]
This works with the Material UI theme but the opacity of the background is missing, it's instead opaque.

**Comment by mrodalgaard** [comment]
@wldcordeiro; the new package release should solve this. Now the expose tab body is set to the same solid color as theme background. Transparent tabs did not look very well.
